using System;
using System.Linq;
using System.Text;
using static System.Console;
using System.Collections.Generic;

namespace TestCodes
{
	class Problem_9987
	{
		public static IEnumerable<Pokemon> pokemons => new List<Pokemon>
		{
			new Pokemon { Index = 001, Name = "Bulbasaur", Type = "Grass Poison" },
			new Pokemon { Index = 002, Name = "Ivysaur", Type = "Grass Poison" },
			new Pokemon { Index = 003, Name = "Venusaur", Type = "Grass Poison" },
			new Pokemon { Index = 004, Name = "Charmander", Type = "Fire" },
			new Pokemon { Index = 005, Name = "Charmeleon", Type = "Fire" },
			new Pokemon { Index = 006, Name = "Charizard", Type = "Fire Flying" },
			new Pokemon { Index = 007, Name = "Squirtle", Type = "Water" },
			new Pokemon { Index = 008, Name = "Wartortle", Type = "Water" },
			new Pokemon { Index = 009, Name = "Blastoise", Type = "Water" },
			new Pokemon { Index = 010, Name = "Caterpie", Type = "Bug" },
			new Pokemon { Index = 011, Name = "Metapod", Type = "Bug" },
			new Pokemon { Index = 012, Name = "Butterfree", Type = "Bug Flying" },
			new Pokemon { Index = 013, Name = "Weedle", Type = "Bug Poison" },
			new Pokemon { Index = 014, Name = "Kakuna", Type = "Bug Poison" },
			new Pokemon { Index = 015, Name = "Beedrill", Type = "Bug Poison" },
			new Pokemon { Index = 016, Name = "Pidgey", Type = "Normal Flying" },
			new Pokemon { Index = 017, Name = "Pidgeotto", Type = "Normal Flying" },
			new Pokemon { Index = 018, Name = "Pidgeot", Type = "Normal Flying" },
			new Pokemon { Index = 019, Name = "Rattata", Type = "Normal" },
			new Pokemon { Index = 020, Name = "Raticate", Type = "Normal" },
			new Pokemon { Index = 021, Name = "Spearow", Type = "Normal Flying" },
			new Pokemon { Index = 022, Name = "Fearow", Type = "Normal Flying" },
			new Pokemon { Index = 023, Name = "Ekans", Type = "Poison" },
			new Pokemon { Index = 024, Name = "Arbok", Type = "Poison" },
			new Pokemon { Index = 025, Name = "Pikachu", Type = "Electric" },
			new Pokemon { Index = 026, Name = "Raichu", Type = "Electric" },
			new Pokemon { Index = 027, Name = "Sandshrew", Type = "Ground" },
			new Pokemon { Index = 028, Name = "Sandslash", Type = "Ground" },
			new Pokemon { Index = 029, Name = "Nidoran♀", Type = "Poison" },
			new Pokemon { Index = 030, Name = "Nidorina", Type = "Poison" },
			new Pokemon { Index = 031, Name = "Nidoqueen", Type = "Poison Ground" },
			new Pokemon { Index = 032, Name = "Nidoran♂", Type = "Poison" },
			new Pokemon { Index = 033, Name = "Nidorino", Type = "Poison" },
			new Pokemon { Index = 034, Name = "Nidoking", Type = "Poison Ground" },
			new Pokemon { Index = 035, Name = "Clefairy", Type = "Fairy" },
			new Pokemon { Index = 036, Name = "Clefable", Type = "Fairy" },
			new Pokemon { Index = 037, Name = "Vulpix", Type = "Fire" },
			new Pokemon { Index = 038, Name = "Ninetales", Type = "Fire" },
			new Pokemon { Index = 039, Name = "Jigglypuff", Type = "Normal Fairy" },
			new Pokemon { Index = 040, Name = "Wigglytuff", Type = "Normal Fairy" },
			new Pokemon { Index = 041, Name = "Zubat", Type = "Poison Flying" },
			new Pokemon { Index = 042, Name = "Golbat", Type = "Poison Flying" },
			new Pokemon { Index = 043, Name = "Oddish", Type = "Grass Poison" },
			new Pokemon { Index = 044, Name = "Gloom", Type = "Grass Poison" },
			new Pokemon { Index = 045, Name = "Vileplume", Type = "Grass Poison" },
			new Pokemon { Index = 046, Name = "Paras", Type = "Bug Grass" },
			new Pokemon { Index = 047, Name = "Parasect", Type = "Bug Grass" },
			new Pokemon { Index = 048, Name = "Venonat", Type = "Bug Poison" },
			new Pokemon { Index = 049, Name = "Venomoth", Type = "Bug Poison" },
			new Pokemon { Index = 050, Name = "Diglett", Type = "Ground" },
			new Pokemon { Index = 051, Name = "Dugtrio", Type = "Ground" },
			new Pokemon { Index = 052, Name = "Meowth", Type = "Normal" },
			new Pokemon { Index = 053, Name = "Persian", Type = "Normal" },
			new Pokemon { Index = 054, Name = "Psyduck", Type = "Water" },
			new Pokemon { Index = 055, Name = "Golduck", Type = "Water" },
			new Pokemon { Index = 056, Name = "Mankey", Type = "Fighting" },
			new Pokemon { Index = 057, Name = "Primeape", Type = "Fighting" },
			new Pokemon { Index = 058, Name = "Growlithe", Type = "Fire" },
			new Pokemon { Index = 059, Name = "Arcanine", Type = "Fire" },
			new Pokemon { Index = 060, Name = "Poliwag", Type = "Water" },
			new Pokemon { Index = 061, Name = "Poliwhirl", Type = "Water" },
			new Pokemon { Index = 062, Name = "Poliwrath", Type = "Water Fighting" },
			new Pokemon { Index = 063, Name = "Abra", Type = "Psychic" },
			new Pokemon { Index = 064, Name = "Kadabra", Type = "Psychic" },
			new Pokemon { Index = 065, Name = "Alakazam", Type = "Psychic" },
			new Pokemon { Index = 066, Name = "Machop", Type = "Fighting" },
			new Pokemon { Index = 067, Name = "Machoke", Type = "Fighting" },
			new Pokemon { Index = 068, Name = "Machamp", Type = "Fighting" },
			new Pokemon { Index = 069, Name = "Bellsprout", Type = "Grass Poison" },
			new Pokemon { Index = 070, Name = "Weepinbell", Type = "Grass Poison" },
			new Pokemon { Index = 071, Name = "Victreebel", Type = "Grass Poison" },
			new Pokemon { Index = 072, Name = "Tentacool", Type = "Water Poison" },
			new Pokemon { Index = 073, Name = "Tentacruel", Type = "Water Poison" },
			new Pokemon { Index = 074, Name = "Geodude", Type = "Rock Ground" },
			new Pokemon { Index = 075, Name = "Graveler", Type = "Rock Ground" },
			new Pokemon { Index = 076, Name = "Golem", Type = "Rock Ground" },
			new Pokemon { Index = 077, Name = "Ponyta", Type = "Fire" },
			new Pokemon { Index = 078, Name = "Rapidash", Type = "Fire" },
			new Pokemon { Index = 079, Name = "Slowpoke", Type = "Water Psychic" },
			new Pokemon { Index = 080, Name = "Slowbro", Type = "Water Psychic" },
			new Pokemon { Index = 081, Name = "Magnemite", Type = "Electric Steel" },
			new Pokemon { Index = 082, Name = "Magneton", Type = "Electric Steel" },
			new Pokemon { Index = 083, Name = "Farfetch'd", Type = "Normal Flying" },
			new Pokemon { Index = 084, Name = "Doduo", Type = "Normal Flying" },
			new Pokemon { Index = 085, Name = "Dodrio", Type = "Normal Flying" },
			new Pokemon { Index = 086, Name = "Seel", Type = "Water" },
			new Pokemon { Index = 087, Name = "Dewgong", Type = "Water Ice" },
			new Pokemon { Index = 088, Name = "Grimer", Type = "Poison" },
			new Pokemon { Index = 089, Name = "Muk", Type = "Poison" },
			new Pokemon { Index = 090, Name = "Shellder", Type = "Water" },
			new Pokemon { Index = 091, Name = "Cloyster", Type = "Water Ice" },
			new Pokemon { Index = 092, Name = "Gastly", Type = "Ghost Poison" },
			new Pokemon { Index = 093, Name = "Haunter", Type = "Ghost Poison" },
			new Pokemon { Index = 094, Name = "Gengar", Type = "Ghost Poison" },
			new Pokemon { Index = 095, Name = "Onix", Type = "Rock Ground" },
			new Pokemon { Index = 096, Name = "Drowzee", Type = "Psychic" },
			new Pokemon { Index = 097, Name = "Hypno", Type = "Psychic" },
			new Pokemon { Index = 098, Name = "Krabby", Type = "Water" },
			new Pokemon { Index = 099, Name = "Kingler", Type = "Water" },
			new Pokemon { Index = 100, Name = "Voltorb", Type = "Electric" },
			new Pokemon { Index = 101, Name = "Electrode", Type = "Electric" },
			new Pokemon { Index = 102, Name = "Exeggcute", Type = "Grass Psychic" },
			new Pokemon { Index = 103, Name = "Exeggutor", Type = "Grass Psychic" },
			new Pokemon { Index = 104, Name = "Cubone", Type = "Ground" },
			new Pokemon { Index = 105, Name = "Marowak", Type = "Ground" },
			new Pokemon { Index = 106, Name = "Hitmonlee", Type = "Fighting" },
			new Pokemon { Index = 107, Name = "Hitmonchan", Type = "Fighting" },
			new Pokemon { Index = 108, Name = "Lickitung", Type = "Normal" },
			new Pokemon { Index = 109, Name = "Koffing", Type = "Poison" },
			new Pokemon { Index = 110, Name = "Weezing", Type = "Poison" },
			new Pokemon { Index = 111, Name = "Rhyhorn", Type = "Ground Rock" },
			new Pokemon { Index = 112, Name = "Rhydon", Type = "Ground Rock" },
			new Pokemon { Index = 113, Name = "Chansey", Type = "Normal" },
			new Pokemon { Index = 114, Name = "Tangela", Type = "Grass" },
			new Pokemon { Index = 115, Name = "Kangaskhan", Type = "Normal" },
			new Pokemon { Index = 116, Name = "Horsea", Type = "Water" },
			new Pokemon { Index = 117, Name = "Seadra", Type = "Water" },
			new Pokemon { Index = 118, Name = "Goldeen", Type = "Water" },
			new Pokemon { Index = 119, Name = "Seaking", Type = "Water" },
			new Pokemon { Index = 120, Name = "Staryu", Type = "Water" },
			new Pokemon { Index = 121, Name = "Starmie", Type = "Water Psychic" },
			new Pokemon { Index = 122, Name = "Mr. Mime", Type = "Psychic Fairy" },
			new Pokemon { Index = 123, Name = "Scyther", Type = "Bug Flying" },
			new Pokemon { Index = 124, Name = "Jynx", Type = "Ice Psychic" },
			new Pokemon { Index = 125, Name = "Electabuzz", Type = "Electric" },
			new Pokemon { Index = 126, Name = "Magmar", Type = "Fire" },
			new Pokemon { Index = 127, Name = "Pinsir", Type = "Bug" },
			new Pokemon { Index = 128, Name = "Tauros", Type = "Normal" },
			new Pokemon { Index = 129, Name = "Magikarp", Type = "Water" },
			new Pokemon { Index = 130, Name = "Gyarados", Type = "Water Flying" },
			new Pokemon { Index = 131, Name = "Lapras", Type = "Water Ice" },
			new Pokemon { Index = 132, Name = "Ditto", Type = "Normal" },
			new Pokemon { Index = 133, Name = "Eevee", Type = "Normal" },
			new Pokemon { Index = 134, Name = "Vaporeon", Type = "Water" },
			new Pokemon { Index = 135, Name = "Jolteon", Type = "Electric" },
			new Pokemon { Index = 136, Name = "Flareon", Type = "Fire" },
			new Pokemon { Index = 137, Name = "Porygon", Type = "Normal" },
			new Pokemon { Index = 138, Name = "Omanyte", Type = "Rock Water" },
			new Pokemon { Index = 139, Name = "Omastar", Type = "Rock Water" },
			new Pokemon { Index = 140, Name = "Kabuto", Type = "Rock Water" },
			new Pokemon { Index = 141, Name = "Kabutops", Type = "Rock Water" },
			new Pokemon { Index = 142, Name = "Aerodactyl", Type = "Rock Flying" },
			new Pokemon { Index = 143, Name = "Snorlax", Type = "Normal" },
			new Pokemon { Index = 144, Name = "Articuno", Type = "Ice Flying" },
			new Pokemon { Index = 145, Name = "Zapdos", Type = "Electric Flying" },
			new Pokemon { Index = 146, Name = "Moltres", Type = "Fire Flying" },
			new Pokemon { Index = 147, Name = "Dratini", Type = "Dragon" },
			new Pokemon { Index = 148, Name = "Dragonair", Type = "Dragon" },
			new Pokemon { Index = 149, Name = "Dragonite", Type = "Dragon Flying" },
			new Pokemon { Index = 150, Name = "Mewtwo", Type = "Psychic" },
			new Pokemon { Index = 151, Name = "Mew", Type = "Psychic" },
			new Pokemon { Index = 152, Name = "Chikorita", Type = "Grass" },
			new Pokemon { Index = 153, Name = "Bayleef", Type = "Grass" },
			new Pokemon { Index = 154, Name = "Meganium", Type = "Grass" },
			new Pokemon { Index = 155, Name = "Cyndaquil", Type = "Fire" },
			new Pokemon { Index = 156, Name = "Quilava", Type = "Fire" },
			new Pokemon { Index = 157, Name = "Typhlosion", Type = "Fire" },
			new Pokemon { Index = 158, Name = "Totodile", Type = "Water" },
			new Pokemon { Index = 159, Name = "Croconaw", Type = "Water" },
			new Pokemon { Index = 160, Name = "Feraligatr", Type = "Water" },
			new Pokemon { Index = 161, Name = "Sentret", Type = "Normal" },
			new Pokemon { Index = 162, Name = "Furret", Type = "Normal" },
			new Pokemon { Index = 163, Name = "Hoothoot", Type = "Normal Flying" },
			new Pokemon { Index = 164, Name = "Noctowl", Type = "Normal Flying" },
			new Pokemon { Index = 165, Name = "Ledyba", Type = "Bug Flying" },
			new Pokemon { Index = 166, Name = "Ledian", Type = "Bug Flying" },
			new Pokemon { Index = 167, Name = "Spinarak", Type = "Bug Poison" },
			new Pokemon { Index = 168, Name = "Ariados", Type = "Bug Poison" },
			new Pokemon { Index = 169, Name = "Crobat", Type = "Poison Flying" },
			new Pokemon { Index = 170, Name = "Chinchou", Type = "Water Electric" },
			new Pokemon { Index = 171, Name = "Lanturn", Type = "Water Electric" },
			new Pokemon { Index = 172, Name = "Pichu", Type = "Electric" },
			new Pokemon { Index = 173, Name = "Cleffa", Type = "Fairy" },
			new Pokemon { Index = 174, Name = "Igglybuff", Type = "Normal Fairy" },
			new Pokemon { Index = 175, Name = "Togepi", Type = "Fairy" },
			new Pokemon { Index = 176, Name = "Togetic", Type = "Fairy Flying" },
			new Pokemon { Index = 177, Name = "Natu", Type = "Psychic Flying" },
			new Pokemon { Index = 178, Name = "Xatu", Type = "Psychic Flying" },
			new Pokemon { Index = 179, Name = "Mareep", Type = "Electric" },
			new Pokemon { Index = 180, Name = "Flaaffy", Type = "Electric" },
			new Pokemon { Index = 181, Name = "Ampharos", Type = "Electric" },
			new Pokemon { Index = 182, Name = "Bellossom", Type = "Grass" },
			new Pokemon { Index = 183, Name = "Marill", Type = "Water Fairy" },
			new Pokemon { Index = 184, Name = "Azumarill", Type = "Water Fairy" },
			new Pokemon { Index = 185, Name = "Sudowoodo", Type = "Rock" },
			new Pokemon { Index = 186, Name = "Politoed", Type = "Water" },
			new Pokemon { Index = 187, Name = "Hoppip", Type = "Grass Flying" },
			new Pokemon { Index = 188, Name = "Skiploom", Type = "Grass Flying" },
			new Pokemon { Index = 189, Name = "Jumpluff", Type = "Grass Flying" },
			new Pokemon { Index = 190, Name = "Aipom", Type = "Normal" },
			new Pokemon { Index = 191, Name = "Sunkern", Type = "Grass" },
			new Pokemon { Index = 192, Name = "Sunflora", Type = "Grass" },
			new Pokemon { Index = 193, Name = "Yanma", Type = "Bug Flying" },
			new Pokemon { Index = 194, Name = "Wooper", Type = "Water Ground" },
			new Pokemon { Index = 195, Name = "Quagsire", Type = "Water Ground" },
			new Pokemon { Index = 196, Name = "Espeon", Type = "Psychic" },
			new Pokemon { Index = 197, Name = "Umbreon", Type = "Dark" },
			new Pokemon { Index = 198, Name = "Murkrow", Type = "Dark Flying" },
			new Pokemon { Index = 199, Name = "Slowking", Type = "Water Psychic" },
			new Pokemon { Index = 200, Name = "Misdreavus", Type = "Ghost" },
			new Pokemon { Index = 201, Name = "Unown", Type = "Psychic" },
			new Pokemon { Index = 202, Name = "Wobbuffet", Type = "Psychic" },
			new Pokemon { Index = 203, Name = "Girafarig", Type = "Normal Psychic" },
			new Pokemon { Index = 204, Name = "Pineco", Type = "Bug" },
			new Pokemon { Index = 205, Name = "Forretress", Type = "Bug Steel" },
			new Pokemon { Index = 206, Name = "Dunsparce", Type = "Normal" },
			new Pokemon { Index = 207, Name = "Gligar", Type = "Ground Flying" },
			new Pokemon { Index = 208, Name = "Steelix", Type = "Steel Ground" },
			new Pokemon { Index = 209, Name = "Snubbull", Type = "Fairy" },
			new Pokemon { Index = 210, Name = "Granbull", Type = "Fairy" },
			new Pokemon { Index = 211, Name = "Qwilfish", Type = "Water Poison" },
			new Pokemon { Index = 212, Name = "Scizor", Type = "Bug Steel" },
			new Pokemon { Index = 213, Name = "Shuckle", Type = "Bug Rock" },
			new Pokemon { Index = 214, Name = "Heracross", Type = "Bug Fighting" },
			new Pokemon { Index = 215, Name = "Sneasel", Type = "Dark Ice" },
			new Pokemon { Index = 216, Name = "Teddiursa", Type = "Normal" },
			new Pokemon { Index = 217, Name = "Ursaring", Type = "Normal" },
			new Pokemon { Index = 218, Name = "Slugma", Type = "Fire" },
			new Pokemon { Index = 219, Name = "Magcargo", Type = "Fire Rock" },
			new Pokemon { Index = 220, Name = "Swinub", Type = "Ice Ground" },
			new Pokemon { Index = 221, Name = "Piloswine", Type = "Ice Ground" },
			new Pokemon { Index = 222, Name = "Corsola", Type = "Water Rock" },
			new Pokemon { Index = 223, Name = "Remoraid", Type = "Water" },
			new Pokemon { Index = 224, Name = "Octillery", Type = "Water" },
			new Pokemon { Index = 225, Name = "Delibird", Type = "Ice Flying" },
			new Pokemon { Index = 226, Name = "Mantine", Type = "Water Flying" },
			new Pokemon { Index = 227, Name = "Skarmory", Type = "Steel Flying" },
			new Pokemon { Index = 228, Name = "Houndour", Type = "Dark Fire" },
			new Pokemon { Index = 229, Name = "Houndoom", Type = "Dark Fire" },
			new Pokemon { Index = 230, Name = "Kingdra", Type = "Water Dragon" },
			new Pokemon { Index = 231, Name = "Phanpy", Type = "Ground" },
			new Pokemon { Index = 232, Name = "Donphan", Type = "Ground" },
			new Pokemon { Index = 233, Name = "Porygon2", Type = "Normal" },
			new Pokemon { Index = 234, Name = "Stantler", Type = "Normal" },
			new Pokemon { Index = 235, Name = "Smeargle", Type = "Normal" },
			new Pokemon { Index = 236, Name = "Tyrogue", Type = "Fighting" },
			new Pokemon { Index = 237, Name = "Hitmontop", Type = "Fighting" },
			new Pokemon { Index = 238, Name = "Smoochum", Type = "Ice Psychic" },
			new Pokemon { Index = 239, Name = "Elekid", Type = "Electric" },
			new Pokemon { Index = 240, Name = "Magby", Type = "Fire" },
			new Pokemon { Index = 241, Name = "Miltank", Type = "Normal" },
			new Pokemon { Index = 242, Name = "Blissey", Type = "Normal" },
			new Pokemon { Index = 243, Name = "Raikou", Type = "Electric" },
			new Pokemon { Index = 244, Name = "Entei", Type = "Fire" },
			new Pokemon { Index = 245, Name = "Suicune", Type = "Water" },
			new Pokemon { Index = 246, Name = "Larvitar", Type = "Rock Ground" },
			new Pokemon { Index = 247, Name = "Pupitar", Type = "Rock Ground" },
			new Pokemon { Index = 248, Name = "Tyranitar", Type = "Rock Dark" },
			new Pokemon { Index = 249, Name = "Lugia", Type = "Psychic Flying" },
			new Pokemon { Index = 250, Name = "Ho-oh", Type = "Fire Flying" },
			new Pokemon { Index = 251, Name = "Celebi", Type = "Psychic Grass" },
			new Pokemon { Index = 252, Name = "Treecko", Type = "Grass" },
			new Pokemon { Index = 253, Name = "Grovyle", Type = "Grass" },
			new Pokemon { Index = 254, Name = "Sceptile", Type = "Grass" },
			new Pokemon { Index = 255, Name = "Torchic", Type = "Fire" },
			new Pokemon { Index = 256, Name = "Combusken", Type = "Fire Fighting" },
			new Pokemon { Index = 257, Name = "Blaziken", Type = "Fire Fighting" },
			new Pokemon { Index = 258, Name = "Mudkip", Type = "Water" },
			new Pokemon { Index = 259, Name = "Marshtomp", Type = "Water Ground" },
			new Pokemon { Index = 260, Name = "Swampert", Type = "Water Ground" },
			new Pokemon { Index = 261, Name = "Poochyena", Type = "Dark" },
			new Pokemon { Index = 262, Name = "Mightyena", Type = "Dark" },
			new Pokemon { Index = 263, Name = "Zigzagoon", Type = "Normal" },
			new Pokemon { Index = 264, Name = "Linoone", Type = "Normal" },
			new Pokemon { Index = 265, Name = "Wurmple", Type = "Bug" },
			new Pokemon { Index = 266, Name = "Silcoon", Type = "Bug" },
			new Pokemon { Index = 267, Name = "Beautifly", Type = "Bug Flying" },
			new Pokemon { Index = 268, Name = "Cascoon", Type = "Bug" },
			new Pokemon { Index = 269, Name = "Dustox", Type = "Bug Poison" },
			new Pokemon { Index = 270, Name = "Lotad", Type = "Water Grass" },
			new Pokemon { Index = 271, Name = "Lombre", Type = "Water Grass" },
			new Pokemon { Index = 272, Name = "Ludicolo", Type = "Water Grass" },
			new Pokemon { Index = 273, Name = "Seedot", Type = "Grass" },
			new Pokemon { Index = 274, Name = "Nuzleaf", Type = "Grass Dark" },
			new Pokemon { Index = 275, Name = "Shiftry", Type = "Grass Dark" },
			new Pokemon { Index = 276, Name = "Taillow", Type = "Normal Flying" },
			new Pokemon { Index = 277, Name = "Swellow", Type = "Normal Flying" },
			new Pokemon { Index = 278, Name = "Wingull", Type = "Water Flying" },
			new Pokemon { Index = 279, Name = "Pelipper", Type = "Water Flying" },
			new Pokemon { Index = 280, Name = "Ralts", Type = "Psychic Fairy" },
			new Pokemon { Index = 281, Name = "Kirlia", Type = "Psychic Fairy" },
			new Pokemon { Index = 282, Name = "Gardevoir", Type = "Psychic Fairy" },
			new Pokemon { Index = 283, Name = "Surskit", Type = "Bug Water" },
			new Pokemon { Index = 284, Name = "Masquerain", Type = "Bug Flying" },
			new Pokemon { Index = 285, Name = "Shroomish", Type = "Grass" },
			new Pokemon { Index = 286, Name = "Breloom", Type = "Grass Fighting" },
			new Pokemon { Index = 287, Name = "Slakoth", Type = "Normal" },
			new Pokemon { Index = 288, Name = "Vigoroth", Type = "Normal" },
			new Pokemon { Index = 289, Name = "Slaking", Type = "Normal" },
			new Pokemon { Index = 290, Name = "Nincada", Type = "Bug Ground" },
			new Pokemon { Index = 291, Name = "Ninjask", Type = "Bug Flying" },
			new Pokemon { Index = 292, Name = "Shedinja", Type = "Bug Ghost" },
			new Pokemon { Index = 293, Name = "Whismur", Type = "Normal" },
			new Pokemon { Index = 294, Name = "Loudred", Type = "Normal" },
			new Pokemon { Index = 295, Name = "Exploud", Type = "Normal" },
			new Pokemon { Index = 296, Name = "Makuhita", Type = "Fighting" },
			new Pokemon { Index = 297, Name = "Hariyama", Type = "Fighting" },
			new Pokemon { Index = 298, Name = "Azurill", Type = "Normal Fairy" },
			new Pokemon { Index = 299, Name = "Nosepass", Type = "Rock" },
			new Pokemon { Index = 300, Name = "Skitty", Type = "Normal" },
			new Pokemon { Index = 301, Name = "Delcatty", Type = "Normal" },
			new Pokemon { Index = 302, Name = "Sableye", Type = "Dark Ghost" },
			new Pokemon { Index = 303, Name = "Mawile", Type = "Steel Fairy" },
			new Pokemon { Index = 304, Name = "Aron", Type = "Steel Rock" },
			new Pokemon { Index = 305, Name = "Lairon", Type = "Steel Rock" },
			new Pokemon { Index = 306, Name = "Aggron", Type = "Steel Rock" },
			new Pokemon { Index = 307, Name = "Meditite", Type = "Fighting Psychic" },
			new Pokemon { Index = 308, Name = "Medicham", Type = "Fighting Psychic" },
			new Pokemon { Index = 309, Name = "Electrike", Type = "Electric" },
			new Pokemon { Index = 310, Name = "Manectric", Type = "Electric" },
			new Pokemon { Index = 311, Name = "Plusle", Type = "Electric" },
			new Pokemon { Index = 312, Name = "Minun", Type = "Electric" },
			new Pokemon { Index = 313, Name = "Volbeat", Type = "Bug" },
			new Pokemon { Index = 314, Name = "Illumise", Type = "Bug" },
			new Pokemon { Index = 315, Name = "Roselia", Type = "Grass Poison" },
			new Pokemon { Index = 316, Name = "Gulpin", Type = "Poison" },
			new Pokemon { Index = 317, Name = "Swalot", Type = "Poison" },
			new Pokemon { Index = 318, Name = "Carvanha", Type = "Water Dark" },
			new Pokemon { Index = 319, Name = "Sharpedo", Type = "Water Dark" },
			new Pokemon { Index = 320, Name = "Wailmer", Type = "Water" },
			new Pokemon { Index = 321, Name = "Wailord", Type = "Water" },
			new Pokemon { Index = 322, Name = "Numel", Type = "Fire Ground" },
			new Pokemon { Index = 323, Name = "Camerupt", Type = "Fire Ground" },
			new Pokemon { Index = 324, Name = "Torkoal", Type = "Fire" },
			new Pokemon { Index = 325, Name = "Spoink", Type = "Psychic" },
			new Pokemon { Index = 326, Name = "Grumpig", Type = "Psychic" },
			new Pokemon { Index = 327, Name = "Spinda", Type = "Normal" },
			new Pokemon { Index = 328, Name = "Trapinch", Type = "Ground" },
			new Pokemon { Index = 329, Name = "Vibrava", Type = "Ground Dragon" },
			new Pokemon { Index = 330, Name = "Flygon", Type = "Ground Dragon" },
			new Pokemon { Index = 331, Name = "Cacnea", Type = "Grass" },
			new Pokemon { Index = 332, Name = "Cacturne", Type = "Grass Dark" },
			new Pokemon { Index = 333, Name = "Swablu", Type = "Normal Flying" },
			new Pokemon { Index = 334, Name = "Altaria", Type = "Dragon Flying" },
			new Pokemon { Index = 335, Name = "Zangoose", Type = "Normal" },
			new Pokemon { Index = 336, Name = "Seviper", Type = "Poison" },
			new Pokemon { Index = 337, Name = "Lunatone", Type = "Rock Psychic" },
			new Pokemon { Index = 338, Name = "Solrock", Type = "Rock Psychic" },
			new Pokemon { Index = 339, Name = "Barboach", Type = "Water Ground" },
			new Pokemon { Index = 340, Name = "Whiscash", Type = "Water Ground" },
			new Pokemon { Index = 341, Name = "Corphish", Type = "Water" },
			new Pokemon { Index = 342, Name = "Crawdaunt", Type = "Water Dark" },
			new Pokemon { Index = 343, Name = "Baltoy", Type = "Ground Psychic" },
			new Pokemon { Index = 344, Name = "Claydol", Type = "Ground Psychic" },
			new Pokemon { Index = 345, Name = "Lileep", Type = "Rock Grass" },
			new Pokemon { Index = 346, Name = "Cradily", Type = "Rock Grass" },
			new Pokemon { Index = 347, Name = "Anorith", Type = "Rock Bug" },
			new Pokemon { Index = 348, Name = "Armaldo", Type = "Rock Bug" },
			new Pokemon { Index = 349, Name = "Feebas", Type = "Water" },
			new Pokemon { Index = 350, Name = "Milotic", Type = "Water" },
			new Pokemon { Index = 351, Name = "Castform", Type = "Normal" },
			new Pokemon { Index = 352, Name = "Kecleon", Type = "Normal" },
			new Pokemon { Index = 353, Name = "Shuppet", Type = "Ghost" },
			new Pokemon { Index = 354, Name = "Banette", Type = "Ghost" },
			new Pokemon { Index = 355, Name = "Duskull", Type = "Ghost" },
			new Pokemon { Index = 356, Name = "Dusclops", Type = "Ghost" },
			new Pokemon { Index = 357, Name = "Tropius", Type = "Grass Flying" },
			new Pokemon { Index = 358, Name = "Chimecho", Type = "Psychic" },
			new Pokemon { Index = 359, Name = "Absol", Type = "Dark" },
			new Pokemon { Index = 360, Name = "Wynaut", Type = "Psychic" },
			new Pokemon { Index = 361, Name = "Snorunt", Type = "Ice" },
			new Pokemon { Index = 362, Name = "Glalie", Type = "Ice" },
			new Pokemon { Index = 363, Name = "Spheal", Type = "Ice Water" },
			new Pokemon { Index = 364, Name = "Sealeo", Type = "Ice Water" },
			new Pokemon { Index = 365, Name = "Walrein", Type = "Ice Water" },
			new Pokemon { Index = 366, Name = "Clamperl", Type = "Water" },
			new Pokemon { Index = 367, Name = "Huntail", Type = "Water" },
			new Pokemon { Index = 368, Name = "Gorebyss", Type = "Water" },
			new Pokemon { Index = 369, Name = "Relicanth", Type = "Water Rock" },
			new Pokemon { Index = 370, Name = "Luvdisc", Type = "Water" },
			new Pokemon { Index = 371, Name = "Bagon", Type = "Dragon" },
			new Pokemon { Index = 372, Name = "Shelgon", Type = "Dragon" },
			new Pokemon { Index = 373, Name = "Salamence", Type = "Dragon Flying" },
			new Pokemon { Index = 374, Name = "Beldum", Type = "Steel Psychic" },
			new Pokemon { Index = 375, Name = "Metang", Type = "Steel Psychic" },
			new Pokemon { Index = 376, Name = "Metagross", Type = "Steel Psychic" },
			new Pokemon { Index = 377, Name = "Regirock", Type = "Rock" },
			new Pokemon { Index = 378, Name = "Regice", Type = "Ice" },
			new Pokemon { Index = 379, Name = "Registeel", Type = "Steel" },
			new Pokemon { Index = 380, Name = "Latias", Type = "Dragon Psychic" },
			new Pokemon { Index = 381, Name = "Latios", Type = "Dragon Psychic" },
			new Pokemon { Index = 382, Name = "Kyogre", Type = "Water" },
			new Pokemon { Index = 383, Name = "Groudon", Type = "Ground" },
			new Pokemon { Index = 384, Name = "Rayquaza", Type = "Dragon Flying" },
			new Pokemon { Index = 385, Name = "Jirachi", Type = "Steel Psychic" },
			new Pokemon { Index = 386, Name = "Deoxys", Type = "Psychic" },
			new Pokemon { Index = 387, Name = "Turtwig", Type = "Grass" },
			new Pokemon { Index = 388, Name = "Grotle", Type = "Grass" },
			new Pokemon { Index = 389, Name = "Torterra", Type = "Grass Ground" },
			new Pokemon { Index = 390, Name = "Chimchar", Type = "Fire" },
			new Pokemon { Index = 391, Name = "Monferno", Type = "Fire Fighting" },
			new Pokemon { Index = 392, Name = "Infernape", Type = "Fire Fighting" },
			new Pokemon { Index = 393, Name = "Piplup", Type = "Water" },
			new Pokemon { Index = 394, Name = "Prinplup", Type = "Water" },
			new Pokemon { Index = 395, Name = "Empoleon", Type = "Water Steel" },
			new Pokemon { Index = 396, Name = "Starly", Type = "Normal Flying" },
			new Pokemon { Index = 397, Name = "Staravia", Type = "Normal Flying" },
			new Pokemon { Index = 398, Name = "Staraptor", Type = "Normal Flying" },
			new Pokemon { Index = 399, Name = "Bidoof", Type = "Normal" },
			new Pokemon { Index = 400, Name = "Bibarel", Type = "Normal Water" },
			new Pokemon { Index = 401, Name = "Kricketot", Type = "Bug" },
			new Pokemon { Index = 402, Name = "Kricketune", Type = "Bug" },
			new Pokemon { Index = 403, Name = "Shinx", Type = "Electric" },
			new Pokemon { Index = 404, Name = "Luxio", Type = "Electric" },
			new Pokemon { Index = 405, Name = "Luxray", Type = "Electric" },
			new Pokemon { Index = 406, Name = "Budew", Type = "Grass Poison" },
			new Pokemon { Index = 407, Name = "Roserade", Type = "Grass Poison" },
			new Pokemon { Index = 408, Name = "Cranidos", Type = "Rock" },
			new Pokemon { Index = 409, Name = "Rampardos", Type = "Rock" },
			new Pokemon { Index = 410, Name = "Shieldon", Type = "Rock Steel" },
			new Pokemon { Index = 411, Name = "Bastiodon", Type = "Rock Steel" },
			new Pokemon { Index = 412, Name = "Burmy", Type = "Bug" },
			new Pokemon { Index = 413, Name = "Wormadam", Type = "Bug Grass" },
			new Pokemon { Index = 414, Name = "Mothim", Type = "Bug Flying" },
			new Pokemon { Index = 415, Name = "Combee", Type = "Bug Flying" },
			new Pokemon { Index = 416, Name = "Vespiquen", Type = "Bug Flying" },
			new Pokemon { Index = 417, Name = "Pachirisu", Type = "Electric" },
			new Pokemon { Index = 418, Name = "Buizel", Type = "Water" },
			new Pokemon { Index = 419, Name = "Floatzel", Type = "Water" },
			new Pokemon { Index = 420, Name = "Cherubi", Type = "Grass" },
			new Pokemon { Index = 421, Name = "Cherrim", Type = "Grass" },
			new Pokemon { Index = 422, Name = "Shellos", Type = "Water" },
			new Pokemon { Index = 423, Name = "Gastrodon", Type = "Water Ground" },
			new Pokemon { Index = 424, Name = "Ambipom", Type = "Normal" },
			new Pokemon { Index = 425, Name = "Drifloon", Type = "Ghost Flying" },
			new Pokemon { Index = 426, Name = "Drifblim", Type = "Ghost Flying" },
			new Pokemon { Index = 427, Name = "Buneary", Type = "Normal" },
			new Pokemon { Index = 428, Name = "Lopunny", Type = "Normal" },
			new Pokemon { Index = 429, Name = "Mismagius", Type = "Ghost" },
			new Pokemon { Index = 430, Name = "Honchkrow", Type = "Dark Flying" },
			new Pokemon { Index = 431, Name = "Glameow", Type = "Normal" },
			new Pokemon { Index = 432, Name = "Purugly", Type = "Normal" },
			new Pokemon { Index = 433, Name = "Chingling", Type = "Psychic" },
			new Pokemon { Index = 434, Name = "Stunky", Type = "Poison Dark" },
			new Pokemon { Index = 435, Name = "Skuntank", Type = "Poison Dark" },
			new Pokemon { Index = 436, Name = "Bronzor", Type = "Steel Psychic" },
			new Pokemon { Index = 437, Name = "Bronzong", Type = "Steel Psychic" },
			new Pokemon { Index = 438, Name = "Bonsly", Type = "Rock" },
			new Pokemon { Index = 439, Name = "Mime Jr.", Type = "Psychic Fairy" },
			new Pokemon { Index = 440, Name = "Happiny", Type = "Normal" },
			new Pokemon { Index = 441, Name = "Chatot", Type = "Normal Flying" },
			new Pokemon { Index = 442, Name = "Spiritomb", Type = "Ghost Dark" },
			new Pokemon { Index = 443, Name = "Gible", Type = "Dragon Ground" },
			new Pokemon { Index = 444, Name = "Gabite", Type = "Dragon Ground" },
			new Pokemon { Index = 445, Name = "Garchomp", Type = "Dragon Ground" },
			new Pokemon { Index = 446, Name = "Munchlax", Type = "Normal" },
			new Pokemon { Index = 447, Name = "Riolu", Type = "Fighting" },
			new Pokemon { Index = 448, Name = "Lucario", Type = "Fighting Steel" },
			new Pokemon { Index = 449, Name = "Hippopotas", Type = "Ground" },
			new Pokemon { Index = 450, Name = "Hippowdon", Type = "Ground" },
			new Pokemon { Index = 451, Name = "Skorupi", Type = "Poison Bug" },
			new Pokemon { Index = 452, Name = "Drapion", Type = "Poison Dark" },
			new Pokemon { Index = 453, Name = "Croagunk", Type = "Poison Fighting" },
			new Pokemon { Index = 454, Name = "Toxicroak", Type = "Poison Fighting" },
			new Pokemon { Index = 455, Name = "Carnivine", Type = "Grass" },
			new Pokemon { Index = 456, Name = "Finneon", Type = "Water" },
			new Pokemon { Index = 457, Name = "Lumineon", Type = "Water" },
			new Pokemon { Index = 458, Name = "Mantyke", Type = "Water Flying" },
			new Pokemon { Index = 459, Name = "Snover", Type = "Grass Ice" },
			new Pokemon { Index = 460, Name = "Abomasnow", Type = "Grass Ice" },
			new Pokemon { Index = 461, Name = "Weavile", Type = "Dark Ice" },
			new Pokemon { Index = 462, Name = "Magnezone", Type = "Electric Steel" },
			new Pokemon { Index = 463, Name = "Lickilicky", Type = "Normal" },
			new Pokemon { Index = 464, Name = "Rhyperior", Type = "Ground Rock" },
			new Pokemon { Index = 465, Name = "Tangrowth", Type = "Grass" },
			new Pokemon { Index = 466, Name = "Electivire", Type = "Electric" },
			new Pokemon { Index = 467, Name = "Magmortar", Type = "Fire" },
			new Pokemon { Index = 468, Name = "Togekiss", Type = "Fairy Flying" },
			new Pokemon { Index = 469, Name = "Yanmega", Type = "Bug Flying" },
			new Pokemon { Index = 470, Name = "Leafeon", Type = "Grass" },
			new Pokemon { Index = 471, Name = "Glaceon", Type = "Ice" },
			new Pokemon { Index = 472, Name = "Gliscor", Type = "Ground Flying" },
			new Pokemon { Index = 473, Name = "Mamoswine", Type = "Ice Ground" },
			new Pokemon { Index = 474, Name = "Porygon-Z", Type = "Normal" },
			new Pokemon { Index = 475, Name = "Gallade", Type = "Psychic Fighting" },
			new Pokemon { Index = 476, Name = "Probopass", Type = "Rock Steel" },
			new Pokemon { Index = 477, Name = "Dusknoir", Type = "Ghost" },
			new Pokemon { Index = 478, Name = "Froslass", Type = "Ice Ghost" },
			new Pokemon { Index = 479, Name = "Rotom", Type = "Electric Ghost" },
			new Pokemon { Index = 480, Name = "Uxie", Type = "Psychic" },
			new Pokemon { Index = 481, Name = "Mesprit", Type = "Psychic" },
			new Pokemon { Index = 482, Name = "Azelf", Type = "Psychic" },
			new Pokemon { Index = 483, Name = "Dialga", Type = "Steel Dragon" },
			new Pokemon { Index = 484, Name = "Palkia", Type = "Water Dragon" },
			new Pokemon { Index = 485, Name = "Heatran", Type = "Fire Steel" },
			new Pokemon { Index = 486, Name = "Regigigas", Type = "Normal" },
			new Pokemon { Index = 487, Name = "Giratina", Type = "Ghost Dragon" },
			new Pokemon { Index = 488, Name = "Cresselia", Type = "Psychic" },
			new Pokemon { Index = 489, Name = "Phione", Type = "Water" },
			new Pokemon { Index = 490, Name = "Manaphy", Type = "Water" },
			new Pokemon { Index = 491, Name = "Darkrai", Type = "Dark" },
			new Pokemon { Index = 492, Name = "Shaymin", Type = "Grass" },
			new Pokemon { Index = 493, Name = "Arceus", Type = "Normal" },
			new Pokemon { Index = 494, Name = "Victini", Type = "Psychic Fire" },
			new Pokemon { Index = 495, Name = "Snivy", Type = "Grass" },
			new Pokemon { Index = 496, Name = "Servine", Type = "Grass" },
			new Pokemon { Index = 497, Name = "Serperior", Type = "Grass" },
			new Pokemon { Index = 498, Name = "Tepig", Type = "Fire" },
			new Pokemon { Index = 499, Name = "Pignite", Type = "Fire Fighting" },
			new Pokemon { Index = 500, Name = "Emboar", Type = "Fire Fighting" },
			new Pokemon { Index = 501, Name = "Oshawott", Type = "Water" },
			new Pokemon { Index = 502, Name = "Dewott", Type = "Water" },
			new Pokemon { Index = 503, Name = "Samurott", Type = "Water" },
			new Pokemon { Index = 504, Name = "Patrat", Type = "Normal" },
			new Pokemon { Index = 505, Name = "Watchog", Type = "Normal" },
			new Pokemon { Index = 506, Name = "Lillipup", Type = "Normal" },
			new Pokemon { Index = 507, Name = "Herdier", Type = "Normal" },
			new Pokemon { Index = 508, Name = "Stoutland", Type = "Normal" },
			new Pokemon { Index = 509, Name = "Purrloin", Type = "Dark" },
			new Pokemon { Index = 510, Name = "Liepard", Type = "Dark" },
			new Pokemon { Index = 511, Name = "Pansage", Type = "Grass" },
			new Pokemon { Index = 512, Name = "Simisage", Type = "Grass" },
			new Pokemon { Index = 513, Name = "Pansear", Type = "Fire" },
			new Pokemon { Index = 514, Name = "Simisear", Type = "Fire" },
			new Pokemon { Index = 515, Name = "Panpour", Type = "Water" },
			new Pokemon { Index = 516, Name = "Simipour", Type = "Water" },
			new Pokemon { Index = 517, Name = "Munna", Type = "Psychic" },
			new Pokemon { Index = 518, Name = "Musharna", Type = "Psychic" },
			new Pokemon { Index = 519, Name = "Pidove", Type = "Normal Flying" },
			new Pokemon { Index = 520, Name = "Tranquill", Type = "Normal Flying" },
			new Pokemon { Index = 521, Name = "Unfezant", Type = "Normal Flying" },
			new Pokemon { Index = 522, Name = "Blitzle", Type = "Electric" },
			new Pokemon { Index = 523, Name = "Zebstrika", Type = "Electric" },
			new Pokemon { Index = 524, Name = "Roggenrola", Type = "Rock" },
			new Pokemon { Index = 525, Name = "Boldore", Type = "Rock" },
			new Pokemon { Index = 526, Name = "Gigalith", Type = "Rock" },
			new Pokemon { Index = 527, Name = "Woobat", Type = "Psychic Flying" },
			new Pokemon { Index = 528, Name = "Swoobat", Type = "Psychic Flying" },
			new Pokemon { Index = 529, Name = "Drilbur", Type = "Ground" },
			new Pokemon { Index = 530, Name = "Excadrill", Type = "Ground Steel" },
			new Pokemon { Index = 531, Name = "Audino", Type = "Normal" },
			new Pokemon { Index = 532, Name = "Timburr", Type = "Fighting" },
			new Pokemon { Index = 533, Name = "Gurdurr", Type = "Fighting" },
			new Pokemon { Index = 534, Name = "Conkeldurr", Type = "Fighting" },
			new Pokemon { Index = 535, Name = "Tympole", Type = "Water" },
			new Pokemon { Index = 536, Name = "Palpitoad", Type = "Water Ground" },
			new Pokemon { Index = 537, Name = "Seismitoad", Type = "Water Ground" },
			new Pokemon { Index = 538, Name = "Throh", Type = "Fighting" },
			new Pokemon { Index = 539, Name = "Sawk", Type = "Fighting" },
			new Pokemon { Index = 540, Name = "Sewaddle", Type = "Bug Grass" },
			new Pokemon { Index = 541, Name = "Swadloon", Type = "Bug Grass" },
			new Pokemon { Index = 542, Name = "Leavanny", Type = "Bug Grass" },
			new Pokemon { Index = 543, Name = "Venipede", Type = "Bug Poison" },
			new Pokemon { Index = 544, Name = "Whirlipede", Type = "Bug Poison" },
			new Pokemon { Index = 545, Name = "Scolipede", Type = "Bug Poison" },
			new Pokemon { Index = 546, Name = "Cottonee", Type = "Grass Fairy" },
			new Pokemon { Index = 547, Name = "Whimsicott", Type = "Grass Fairy" },
			new Pokemon { Index = 548, Name = "Petilil", Type = "Grass" },
			new Pokemon { Index = 549, Name = "Lilligant", Type = "Grass" },
			new Pokemon { Index = 550, Name = "Basculin", Type = "Water" },
			new Pokemon { Index = 551, Name = "Sandile", Type = "Ground Dark" },
			new Pokemon { Index = 552, Name = "Krokorok", Type = "Ground Dark" },
			new Pokemon { Index = 553, Name = "Krookodile", Type = "Ground Dark" },
			new Pokemon { Index = 554, Name = "Darumaka", Type = "Fire" },
			new Pokemon { Index = 555, Name = "Darmanitan", Type = "Fire" },
			new Pokemon { Index = 556, Name = "Maractus", Type = "Grass" },
			new Pokemon { Index = 557, Name = "Dwebble", Type = "Bug Rock" },
			new Pokemon { Index = 558, Name = "Crustle", Type = "Bug Rock" },
			new Pokemon { Index = 559, Name = "Scraggy", Type = "Dark Fighting" },
			new Pokemon { Index = 560, Name = "Scrafty", Type = "Dark Fighting" },
			new Pokemon { Index = 561, Name = "Sigilyph", Type = "Psychic Flying" },
			new Pokemon { Index = 562, Name = "Yamask", Type = "Ghost" },
			new Pokemon { Index = 563, Name = "Cofagrigus", Type = "Ghost" },
			new Pokemon { Index = 564, Name = "Tirtouga", Type = "Water Rock" },
			new Pokemon { Index = 565, Name = "Carracosta", Type = "Water Rock" },
			new Pokemon { Index = 566, Name = "Archen", Type = "Rock Flying" },
			new Pokemon { Index = 567, Name = "Archeops", Type = "Rock Flying" },
			new Pokemon { Index = 568, Name = "Trubbish", Type = "Poison" },
			new Pokemon { Index = 569, Name = "Garbodor", Type = "Poison" },
			new Pokemon { Index = 570, Name = "Zorua", Type = "Dark" },
			new Pokemon { Index = 571, Name = "Zoroark", Type = "Dark" },
			new Pokemon { Index = 572, Name = "Minccino", Type = "Normal" },
			new Pokemon { Index = 573, Name = "Cinccino", Type = "Normal" },
			new Pokemon { Index = 574, Name = "Gothita", Type = "Psychic" },
			new Pokemon { Index = 575, Name = "Gothorita", Type = "Psychic" },
			new Pokemon { Index = 576, Name = "Gothitelle", Type = "Psychic" },
			new Pokemon { Index = 577, Name = "Solosis", Type = "Psychic" },
			new Pokemon { Index = 578, Name = "Duosion", Type = "Psychic" },
			new Pokemon { Index = 579, Name = "Reuniclus", Type = "Psychic" },
			new Pokemon { Index = 580, Name = "Ducklett", Type = "Water Flying" },
			new Pokemon { Index = 581, Name = "Swanna", Type = "Water Flying" },
			new Pokemon { Index = 582, Name = "Vanillite", Type = "Ice" },
			new Pokemon { Index = 583, Name = "Vanillish", Type = "Ice" },
			new Pokemon { Index = 584, Name = "Vanilluxe", Type = "Ice" },
			new Pokemon { Index = 585, Name = "Deerling", Type = "Normal Grass" },
			new Pokemon { Index = 586, Name = "Sawsbuck", Type = "Normal Grass" },
			new Pokemon { Index = 587, Name = "Emolga", Type = "Electric Flying" },
			new Pokemon { Index = 588, Name = "Karrablast", Type = "Bug" },
			new Pokemon { Index = 589, Name = "Escavalier", Type = "Bug Steel" },
			new Pokemon { Index = 590, Name = "Foongus", Type = "Grass Poison" },
			new Pokemon { Index = 591, Name = "Amoonguss", Type = "Grass Poison" },
			new Pokemon { Index = 592, Name = "Frillish", Type = "Water Ghost" },
			new Pokemon { Index = 593, Name = "Jellicent", Type = "Water Ghost" },
			new Pokemon { Index = 594, Name = "Alomomola", Type = "Water" },
			new Pokemon { Index = 595, Name = "Joltik", Type = "Bug Electric" },
			new Pokemon { Index = 596, Name = "Galvantula", Type = "Bug Electric" },
			new Pokemon { Index = 597, Name = "Ferroseed", Type = "Grass Steel" },
			new Pokemon { Index = 598, Name = "Ferrothorn", Type = "Grass Steel" },
			new Pokemon { Index = 599, Name = "Klink", Type = "Steel" },
			new Pokemon { Index = 600, Name = "Klang", Type = "Steel" },
			new Pokemon { Index = 601, Name = "Klinklang", Type = "Steel" },
			new Pokemon { Index = 602, Name = "Tynamo", Type = "Electric" },
			new Pokemon { Index = 603, Name = "Eelektrik", Type = "Electric" },
			new Pokemon { Index = 604, Name = "Eelektross", Type = "Electric" },
			new Pokemon { Index = 605, Name = "Elgyem", Type = "Psychic" },
			new Pokemon { Index = 606, Name = "Beheeyem", Type = "Psychic" },
			new Pokemon { Index = 607, Name = "Litwick", Type = "Ghost Fire" },
			new Pokemon { Index = 608, Name = "Lampent", Type = "Ghost Fire" },
			new Pokemon { Index = 609, Name = "Chandelure", Type = "Ghost Fire" },
			new Pokemon { Index = 610, Name = "Axew", Type = "Dragon" },
			new Pokemon { Index = 611, Name = "Fraxure", Type = "Dragon" },
			new Pokemon { Index = 612, Name = "Haxorus", Type = "Dragon" },
			new Pokemon { Index = 613, Name = "Cubchoo", Type = "Ice" },
			new Pokemon { Index = 614, Name = "Beartic", Type = "Ice" },
			new Pokemon { Index = 615, Name = "Cryogonal", Type = "Ice" },
			new Pokemon { Index = 616, Name = "Shelmet", Type = "Bug" },
			new Pokemon { Index = 617, Name = "Accelgor", Type = "Bug" },
			new Pokemon { Index = 618, Name = "Stunfisk", Type = "Electric Ground" },
			new Pokemon { Index = 619, Name = "Mienfoo", Type = "Fighting" },
			new Pokemon { Index = 620, Name = "Mienshao", Type = "Fighting" },
			new Pokemon { Index = 621, Name = "Druddigon", Type = "Dragon" },
			new Pokemon { Index = 622, Name = "Golett", Type = "Ground Ghost" },
			new Pokemon { Index = 623, Name = "Golurk", Type = "Ground Ghost" },
			new Pokemon { Index = 624, Name = "Pawniard", Type = "Dark Steel" },
			new Pokemon { Index = 625, Name = "Bisharp", Type = "Dark Steel" },
			new Pokemon { Index = 626, Name = "Bouffalant", Type = "Normal" },
			new Pokemon { Index = 627, Name = "Rufflet", Type = "Normal Flying" },
			new Pokemon { Index = 628, Name = "Braviary", Type = "Normal Flying" },
			new Pokemon { Index = 629, Name = "Vullaby", Type = "Dark Flying" },
			new Pokemon { Index = 630, Name = "Mandibuzz", Type = "Dark Flying" },
			new Pokemon { Index = 631, Name = "Heatmor", Type = "Fire" },
			new Pokemon { Index = 632, Name = "Durant", Type = "Bug Steel" },
			new Pokemon { Index = 633, Name = "Deino", Type = "Dark Dragon" },
			new Pokemon { Index = 634, Name = "Zweilous", Type = "Dark Dragon" },
			new Pokemon { Index = 635, Name = "Hydreigon", Type = "Dark Dragon" },
			new Pokemon { Index = 636, Name = "Larvesta", Type = "Bug Fire" },
			new Pokemon { Index = 637, Name = "Volcarona", Type = "Bug Fire" },
			new Pokemon { Index = 638, Name = "Cobalion", Type = "Steel Fighting" },
			new Pokemon { Index = 639, Name = "Terrakion", Type = "Rock Fighting" },
			new Pokemon { Index = 640, Name = "Virizion", Type = "Grass Fighting" },
			new Pokemon { Index = 641, Name = "Tornadus", Type = "Flying" },
			new Pokemon { Index = 642, Name = "Thundurus", Type = "Electric Flying" },
			new Pokemon { Index = 643, Name = "Reshiram", Type = "Dragon Fire" },
			new Pokemon { Index = 644, Name = "Zekrom", Type = "Dragon Electric" },
			new Pokemon { Index = 645, Name = "Landorus", Type = "Ground Flying" },
			new Pokemon { Index = 646, Name = "Kyurem", Type = "Dragon Ice" },
			new Pokemon { Index = 647, Name = "Keldeo", Type = "Water Fighting" },
			new Pokemon { Index = 648, Name = "Meloetta", Type = "Normal Psychic" },
			new Pokemon { Index = 649, Name = "Genesect", Type = "Bug Steel" },
			new Pokemon { Index = 650, Name = "Chespin", Type = "Grass" },
			new Pokemon { Index = 651, Name = "Quilladin", Type = "Grass" },
			new Pokemon { Index = 652, Name = "Chesnaught", Type = "Grass Fighting" },
			new Pokemon { Index = 653, Name = "Fennekin", Type = "Fire" },
			new Pokemon { Index = 654, Name = "Braixen", Type = "Fire" },
			new Pokemon { Index = 655, Name = "Delphox", Type = "Fire Psychic" },
			new Pokemon { Index = 656, Name = "Froakie", Type = "Water" },
			new Pokemon { Index = 657, Name = "Frogadier", Type = "Water" },
			new Pokemon { Index = 658, Name = "Greninja", Type = "Water Dark" },
			new Pokemon { Index = 659, Name = "Bunnelby", Type = "Normal" },
			new Pokemon { Index = 660, Name = "Diggersby", Type = "Normal Ground" },
			new Pokemon { Index = 661, Name = "Fletchling", Type = "Normal Flying" },
			new Pokemon { Index = 662, Name = "Fletchinder", Type = "Fire Flying" },
			new Pokemon { Index = 663, Name = "Talonflame", Type = "Fire Flying" },
			new Pokemon { Index = 664, Name = "Scatterbug", Type = "Bug" },
			new Pokemon { Index = 665, Name = "Spewpa", Type = "Bug" },
			new Pokemon { Index = 666, Name = "Vivillon", Type = "Bug Flying" },
			new Pokemon { Index = 667, Name = "Litleo", Type = "Fire Normal" },
			new Pokemon { Index = 668, Name = "Pyroar", Type = "Fire Normal" },
			new Pokemon { Index = 669, Name = "Flabébé", Type = "Fairy" },
			new Pokemon { Index = 670, Name = "Floette", Type = "Fairy" },
			new Pokemon { Index = 671, Name = "Florges", Type = "Fairy" },
			new Pokemon { Index = 672, Name = "Skiddo", Type = "Grass" },
			new Pokemon { Index = 673, Name = "Gogoat", Type = "Grass" },
			new Pokemon { Index = 674, Name = "Pancham", Type = "Fighting" },
			new Pokemon { Index = 675, Name = "Pangoro", Type = "Fighting Dark" },
			new Pokemon { Index = 676, Name = "Furfrou", Type = "Normal" },
			new Pokemon { Index = 677, Name = "Espurr", Type = "Psychic" },
			new Pokemon { Index = 678, Name = "Meowstic", Type = "Psychic" },
			new Pokemon { Index = 679, Name = "Honedge", Type = "Steel Ghost" },
			new Pokemon { Index = 680, Name = "Doublade", Type = "Steel Ghost" },
			new Pokemon { Index = 681, Name = "Aegislash", Type = "Steel Ghost" },
			new Pokemon { Index = 682, Name = "Spritzee", Type = "Fairy" },
			new Pokemon { Index = 683, Name = "Aromatisse", Type = "Fairy" },
			new Pokemon { Index = 684, Name = "Swirlix", Type = "Fairy" },
			new Pokemon { Index = 685, Name = "Slurpuff", Type = "Fairy" },
			new Pokemon { Index = 686, Name = "Inkay", Type = "Dark Psychic" },
			new Pokemon { Index = 687, Name = "Malamar", Type = "Dark Psychic" },
			new Pokemon { Index = 688, Name = "Binacle", Type = "Rock Water" },
			new Pokemon { Index = 689, Name = "Barbaracle", Type = "Rock Water" },
			new Pokemon { Index = 690, Name = "Skrelp", Type = "Poison Water" },
			new Pokemon { Index = 691, Name = "Dragalge", Type = "Poison Dragon" },
			new Pokemon { Index = 692, Name = "Clauncher", Type = "Water" },
			new Pokemon { Index = 693, Name = "Clawitzer", Type = "Water" },
			new Pokemon { Index = 694, Name = "Helioptile", Type = "Electric Normal" },
			new Pokemon { Index = 695, Name = "Heliolisk", Type = "Electric Normal" },
			new Pokemon { Index = 696, Name = "Tyrunt", Type = "Rock Dragon" },
			new Pokemon { Index = 697, Name = "Tyrantrum", Type = "Rock Dragon" },
			new Pokemon { Index = 698, Name = "Amaura", Type = "Rock Ice" },
			new Pokemon { Index = 699, Name = "Aurorus", Type = "Rock Ice" },
			new Pokemon { Index = 700, Name = "Sylveon", Type = "Fairy" },
			new Pokemon { Index = 701, Name = "Hawlucha", Type = "Fighting Flying" },
			new Pokemon { Index = 702, Name = "Dedenne", Type = "Electric Fairy" },
			new Pokemon { Index = 703, Name = "Carbink", Type = "Rock Fairy" },
			new Pokemon { Index = 704, Name = "Goomy", Type = "Dragon" },
			new Pokemon { Index = 705, Name = "Sliggoo", Type = "Dragon" },
			new Pokemon { Index = 706, Name = "Goodra", Type = "Dragon" },
			new Pokemon { Index = 707, Name = "Klefki", Type = "Steel Fairy" },
			new Pokemon { Index = 708, Name = "Phantump", Type = "Ghost Grass" },
			new Pokemon { Index = 709, Name = "Trevenant", Type = "Ghost Grass" },
			new Pokemon { Index = 710, Name = "Pumpkaboo", Type = "Ghost Grass" },
			new Pokemon { Index = 711, Name = "Gourgeist", Type = "Ghost Grass" },
			new Pokemon { Index = 712, Name = "Bergmite", Type = "Ice" },
			new Pokemon { Index = 713, Name = "Avalugg", Type = "Ice" },
			new Pokemon { Index = 714, Name = "Noibat", Type = "Flying Dragon" },
			new Pokemon { Index = 715, Name = "Noivern", Type = "Flying Dragon" },
			new Pokemon { Index = 716, Name = "Xerneas", Type = "Fairy" },
			new Pokemon { Index = 717, Name = "Yveltal", Type = "Dark Flying" },
			new Pokemon { Index = 718, Name = "Zygarde", Type = "Dragon Ground" },
		};

		public class Pokemon
		{
			public int Index { get; set; }
			public string Name { get; set; }
			public string Type { get; set; }
		}

		static void Main_9987()
		{
			int num = int.Parse(ReadLine());

			var pokemon = pokemons.FirstOrDefault(c => c.Index == num);

			WriteLine(pokemon.Name);
			WriteLine(pokemon.Type);
		}
	}
}
